### ISSUE TITLE
Improve Social links Sidebar and make footer social icons consistent

### ISSUE THREAD

**Issue by lakshya-dhariwal** [sugarlabs/www#345] opened 2022-01-05 13:23 UTC
When you first open the website the social links sidebar ruins the whole website design and seems out of place.  We can discuss how to make it look better . 

Also the footer social icons are not consistent especially the instagram one. 
Also the instagram logo has this purple colour on hover which adds to the inconsistency

![Screenshot 2022-01-05 at 6 51 25 PM](https://user-images.githubusercontent.com/57823363/148224346-c21a3f35-ef7f-4fd4-ae7f-587a6a2ded97.png)
![Screenshot 2022-01-05 at 6 51 49 PM](https://user-images.githubusercontent.com/57823363/148224401-3f26c41e-d328-4e32-bdbc-261b963601c6.png)
![Screenshot 2022-01-05 at 6 52 09 PM](https://user-images.githubusercontent.com/57823363/148224437-55fe7898-c2b2-4ffd-b9d1-d257d329bdde.png)

**Comment by omnaladkar** [comment] 2022-01-10 13:44
can contribute ?

**Comment by srevinsaju** [comment] 2022-01-10 22:44
Duplicate of #308

**Comment by chimosky** [comment] 2022-01-10 22:55
Seeing as that's closed, I don't think this is a duplication anymore.

**Comment by quozl** [comment] 2022-01-10 22:56
If it can be fixed easily and simply, do so.  [Let's put some lipstick on this pig!](https://en.wikipedia.org/wiki/Lipstick_on_a_pig).

On the other hand, work on this may conflict with https://github.com/sugarlabs/www-sugarlabs/issues/316 so if anyone works on this issue please keep abreast of that issue.

**Comment by lakshya-dhariwal** [comment] 2022-01-12 14:29
@quozl 
So since the site is being shifted to Bootstrap 4 should we fix this issue using bootstrap 4 ( from cdn) as mentioned in #316

**Comment by quozl** [comment] 2022-01-12 23:34
@lakshya-dhariwal, please
* review and test https://github.com/sugarlabs/www-sugarlabs/pull/347 and give your comments,
* base your own pull request on either our _master_ branch or the branch used by https://github.com/sugarlabs/www-sugarlabs/pull/347 rebasing your branch as necessary.
Thanks!

**Comment by nikkuAg** [comment] 2022-01-13 13:26
Can I work on this issue?

**Comment by quozl** [comment] 2022-01-14 04:19
First one to get a pull request merged wins.  Any number of people can work on an issue.

**Comment by nikkuAg** [comment] 2022-01-16 16:18
Hey @quozl,

I want to know which icons are you using like icons from  Font Awesome or from some other.

**Comment by srevinsaju** [comment] 2022-01-16 21:01
@nikkuAg reading the `README.md`, I see

> 7. The current website uses customized versions of a few social media icons (service provided by [Ion Icons](https://ionicons.com)). We do our customizations in a scss file (**/css/ion_icon_customization.scss** file in our case). Please be careful when updating this file. (Also refer to **How to change social media icon colors?** the subsection in **Answers to few questions** section)

**Comment by quozl** [comment] 2022-01-16 21:30
Oops, keyboard shortcut accidental closure.

@srevinsaju, thanks, I didn't remember that.

@nikkuAg, this is how I learned more;

```
git grep ionicons
git log css/ion_icon_customization.scss
find | grep ion | grep icon
```

**Comment by nikkuAg** [comment] 2022-01-20 12:42
Hey @quozl @srevinsaju,

Please review the PR I have created.

**Comment by Jyoti28Dhikale** [comment] 2022-09-19 10:29
hey! is this issue still opened?

**Comment by quozl** [comment] 2022-09-19 11:00
@Jyoti28Dhikale, thanks for asking.  Please review pull request https://github.com/sugarlabs/www-sugarlabs/pull/387.

**Comment by Jyoti28Dhikale** [comment] 2022-09-21 15:15
@quozl  Hello! can you please elaborate what should I do in Remove sidebar social media icons #387

**Comment by quozl** [comment] 2022-09-21 22:58
Sure.  By engaging with Sugar Labs on GitHub, I had presumed you wish to contribute to coding.

Our [Guide to Contributing](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md) lists the tasks that we think of as contributing to coding.  Please read and understand that document, and ask any questions to clarify.

For this particular issue #345 on the web site repository, the next steps are code review, testing, merging, and testing in production.  There is a guide for reviewers.  Pick an appropriate next step and do it?  I do not wish to direct you in detail, because that destroys independence of thought ... I suggest you figure it out from the guide.

**Comment by quozl** [comment] 2023-02-03 23:41
Next step is;

* [ ] make the icons a consistent colour.

**Closed** 2023-02-22 20:21 UTC
